const POPULATION_GROWTH_RATE = 10;
const WASTE_GENERATION_RATE = 0.5;
const MONEY_PER_WASTE = 1;
const PLANET_VALUE_PER_POPULATION = 2;
const PLANET_VALUE_PER_WASTE = -1;
const PLANET_VALUE_PER_EMPTY = 1;
const DESTINATION_DISTANCE_THRESHOLD = 10;
